### PR TITLE
Update Data

### PR DESCRIPTION
**Pull request by curran**
Got most of the data structure filled in.

### CODE REVIEW

**Comment by curran** [comment]
Missing pieces at this point:

 * `total`
 * `increases`
 * `decreases`
 * Filling in missing values as zero (which is questionable, but looks like what was being done before)

**Comment by curran** [comment]
This is exciting! Here's what I'm seeing:

screenshot from 2017-08-07 19-18-04

**Comment by curran** [comment]
New direction for this: http://popdata.unhcr.org/api/stats/time_series_all_years.json?population_type_code=REF

Thanks to Tunzaw for this URL!

**Comment by curran** [comment]
image

**Comment by curran** [comment]
Hi @matthewsmawfield ,

I managed to get the new data working with this visualization.

image

However, there are some issues with the code where the range for year selection is restricted, and the default selected year remains 2012.

**Comment by curran** [comment]
@matthewsmawfield Would you be able to provide any insight as to why the map shapes do not appear for years beyond 2012? I think it has to do with the CShapes data source for map boundaries that differ over the years, but I'm not sure how to remedy this.

**Comment by mayeulk** [comment]
Hi, a few hints that I hope will help:

https://github.com/unhcr/dataviz/blob/120da47d7ed3e8567536623a080a39d229b8cec8/js/worldtopo.json
All thehe "Endyear" (EYEAR) "COWEYEAR":2012
should be replaced into "COWEYEAR":2016

According to this:
https://en.wikipedia.org/wiki/List_of_national_border_changes_since_World_War_I
The only change of border since 2012 is a changes of borders between India and Bangladesh: the biggest territory change is an enclave of less than 0.7 ha and is most likely not a polygon in the simplified worldtopo.json


In Index.html, lines 731 to 733 (check whether the new total has changed)
https://github.com/unhcr/dataviz/blob/120da47d7ed3e8567536623a080a39d229b8cec8/index.html#L731

Also in index.html, lines 1018 sqq and 10244 sqq
I guess replacing the 2016 constant by a variable defined once in the project, as well as refactoring the parts of the code with ".graphTotalOverlay_2012"
 will help future updates easier.

**Comment by mayeulk** [comment]
unhcr_dataviz_works_for_2016
HI,
With the above screenshot I can confirm that making the changes I suggest in my previous message above, into the current master (not curran's branch) makes the app work for 2013 to 2016 as well (is a small glitch: initial view is a greyed map). (The mechanism seems quite similar to what I implemented in my peaceprism project back in 2008/2009, see for instance https://github.com/mayeulk/peaceprism/blob/master/carte_curseur_v1/public/javascripts/slider_event.js )

**Comment by curran** [comment]
Thank you @mayeulk for that very useful information! I used the concept you suggested in my fix.
image
Now the data shows properly up to 2016.

**Comment by matthewsmawfield** [comment]
looking good. i will merge the PR. thanks @mayeulk for your helpful inputs!

**Comment by curran** [comment]
After the year label fix
image

**Pull request merged**
